import { Restaurant, StatusType } from './types';

// Using a generic map-style texture for the preview. 
// In a real app with an API key, this would be: https://maps.googleapis.com/maps/api/staticmap?...
const GENERIC_MAP_IMAGE = "https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&q=80&w=600&h=320";

export const RESTAURANTS: Restaurant[] = [
  {
    id: '1',
    name: 'Cinc Sentits',
    location: "L'Eixample",
    address: "C/ d'Entença, 60, Eixample, 08015 Barcelona",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Cinc+Sentits+Barcelona",
    mapPreviewImage: GENERIC_MAP_IMAGE,
    rating: 4.7,
    conceptTitle: 'Modern Catalan Fine Dining',
    conceptDescription: 'Michelin-starred experience featuring seasonal tasting menus and local ingredients. Sophisticated & private.',
    menuHighlights: ['Seasonal Tasting Menu', 'Local Km0 Ingredients', 'Wine Pairing Available'],
    priceDisplay: '€180 - €230',
    priceValue: 205,
    status: StatusType.AVAILABLE,
  },
  {
    id: '2',
    name: 'Compartir BCN',
    location: "L'Eixample",
    address: "C/ de València, 225, Eixample, 08007 Barcelona",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Compartir+Barcelona",
    mapPreviewImage: GENERIC_MAP_IMAGE,
    rating: 4.5,
    conceptTitle: 'Signature Tasting Menu',
    conceptDescription: 'Full experience by Disfrutar Team. "Panchino" with caviar, Lobster & Premium Wines included.',
    menuHighlights: ['Panchino with Caviar', 'Lobster Salad', 'Premium Wine Selection'],
    priceDisplay: '€ 193',
    priceValue: 193,
    status: StatusType.PROPOSAL_READY,
    isProposalHighlight: true,
  },
  {
    id: '3',
    name: 'Mesaquince',
    location: 'The Brasa Club',
    address: "C/ de Muntaner, 189, Sarrià-Sant Gervasi, 08036 Barcelona",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mesaquince+Barcelona",
    mapPreviewImage: GENERIC_MAP_IMAGE,
    rating: 4.6,
    conceptTitle: 'Argentinian Grill (Sharing Style)',
    conceptDescription: 'Exclusive private atmosphere. Angus Steaks & Sweetbreads. Note: Desserts not included in base price.',
    menuHighlights: ['Argentinian Angus Beef', 'Grilled Sweetbreads', 'Private Room Atmosphere'],
    priceDisplay: '€ 55',
    priceValue: 55,
    status: StatusType.PROPOSAL_READY,
    isProposalHighlight: true,
  },
  {
    id: '4',
    name: 'Mana 75',
    location: 'Barceloneta',
    address: "Pg. de Joan de Borbó, 101, Ciutat Vella, 08039 Barcelona",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mana+75+Barcelona",
    mapPreviewImage: GENERIC_MAP_IMAGE,
    rating: 4.4,
    conceptTitle: 'Authentic Paellas',
    conceptDescription: 'Open kitchen & Sea views. Option for Open Bar (+€45).',
    menuHighlights: ['Seafood Paella', 'Open Bar Option', 'Terrace Seating'],
    priceDisplay: '€ 75',
    priceValue: 75,
    status: StatusType.PROPOSAL_READY,
    isProposalHighlight: true,
    warnings: ['Late Seating 21:30h'],
  },
  {
    id: '5',
    name: 'Azul Rooftop',
    location: 'Barceloneta',
    address: "Pg. de Joan de Borbó, 101, 8th Floor, 08039 Barcelona",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Azul+Rooftop+Barceloneta",
    mapPreviewImage: GENERIC_MAP_IMAGE,
    rating: 4.2,
    conceptTitle: '360º Views & Seafood',
    conceptDescription: 'Stunning rooftop with panoramic city/sea views. Menu focuses on fresh seafood and charcoal-grilled dishes.',
    menuHighlights: ['Fresh Grilled Fish', 'Panoramic Views', 'Signature Cocktails'],
    priceDisplay: '€ 80 - € 110',
    priceValue: 95,
    status: StatusType.PENDING,
  },
  {
    id: '6',
    name: 'Hotel Pullitzer',
    location: 'The Greenhouse',
    address: "C/ de Bergara, 8, Eixample, 08002 Barcelona",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Pulitzer+Barcelona+Greenhouse",
    mapPreviewImage: GENERIC_MAP_IMAGE,
    rating: 4.4,
    conceptTitle: 'Garden Oasis Market Food',
    conceptDescription: 'Relaxed terrace with fresh seasonal dishes.',
    menuHighlights: ['Farm-to-table Vegetables', 'Garden Atmosphere', 'Seasonal Menu'],
    priceDisplay: '€ 50 - € 65',
    priceValue: 57,
    status: StatusType.PENDING,
    warnings: ['Closes at 21:00h (Early Dinner)'],
  },
];